name: Build & Test
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build container
        run: docker build -t plus3it/dependabot-terraform-action:${{ github.sha }} .
      - name: test container
        run: test/test.sh ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPENDENCY_GITHUB_TOKEN: ${{ secrets.DEPENDENCY_GITHUB_TOKEN }}