name: Build & Test &  Release
on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build container
        run: docker build -t plus3it/dependabot-terraform-action:${{ github.sha }} .
      - name: test container
        run: test/test.sh ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPENDENCY_GITHUB_TOKEN: ${{ secrets.DEPENDENCY_GITHUB_TOKEN }}
      - name: login docker registry
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: tag and push latest
        run: |
          docker tag plus3it/dependabot-terraform-action:${{ github.sha }} plus3it/dependabot-terraform-action:latest
          docker push plus3it/dependabot-terraform-action:latest
      - name: tag and push current release tag
        if: github.event_name == 'release' &&  github.event.action == 'published'
        run: |
          docker tag plus3it/dependabot-terraform-action:${{ github.sha }} plus3it/dependabot-terraform-action:${{ github.event.release.tag_name }}
          docker push plus3it/dependabot-terraform-action:${{ github.event.release.tag_name }}
